spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: my-secret-pw
    url: jdbc:mysql://localhost:3314/eav-management
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect